# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: [".rbenv-version", "README.md", "Rakefile", "changelog.md"] # files to exclude
highlighter: 'pygments'
permalink: pretty
markdown: kramdown

title: edap
description: edap
author:
  name: Davide Prati
  # email: lastexxit@gmail.com
  github: edap
  twitter: edapx
  linkedin: davide-prati/21/566/889
  feedname : Edapx
  disqus: edapx
  bio: My name is Davide Prati and that's my website. I'm looking for what's happen tomorrow in the web (hopefully not boring).
  email_md5: 495416d8082cf024cd664937b4feb88a

google_analytics_id : UA-401520-11

rss_path: feed.xml
code_path: code
tags_path: tags

gems:
  - jekyll-redirect-from

