# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: [".rbenv-version", "README.md", "Rakefile", "changelog.md"] # files to exclude
pygments: true

title: edapx
description: edapx
author:
  name: Davide Prati
  # email: lastexxit@gmail.com
  github: edap
  twitter: edpax
  linkedin: davide-prati/21/566/889
  bio: My name is Davide Prati and that's my website. I'm looking for what's happen tomorrow in the web. Hopefully not boring.
  email_md5: 495416d8082cf024cd664937b4feb88a

rss_path: feed.xml
code_path: code.html
tags_path: tags.html

markdown: kramdown


